env:
  global:
    - CC_TEST_REPORTER_ID=0da061981e1c96b99eff879f07dd21a9bb5c61dc98fc18837a02c3f3b91a5425
language: node_js
node_js:
  - "7"
before_script:
  - npm install -g gulp-cli
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - gulp
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT